storm:
  authz:
    policies:
      # belle-tape
      - sa: Lustre-for-Belle-II
        actions:
          - all
        effect: permit
        description: Grant read/write access to belle VO users
        principals:
          - type: vo
            params:
              vo: belle
        # '**' matches any file or directory, at any level of nesting, of a given path
        # '*' matches any file or directory contained in a given path
        paths:
          - /TMP/**
      - sa: Lustre-for-Belle-II
        actions:
          - all
        effect: permit
        description: Grant read/write access to belle VO users with a role of production/lcgadmin
        principals:
          - type: fqan
            params:
              fqan: /belle/Role=production/Capability=NULL
          - type: fqan
            params:
              fqan: /belle/Role=lcgadmin/Capability=NULL
      - sa: Lustre-for-Belle-II
        actions:
          - list
          - read
        effect: permit
        description: Grant read access to belle VO users
        principals:
          - type: vo
            params:
              vo: belle
